name: Continuous Integration
permissions: read-all

on:
  pull_request:
    branches:
      - main
      - devs/**

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: ">=3.10"
      - run: |
          # nosemgrep: generic.ci.security.use-frozen-lockfile.use-frozen-lockfile-pip
          pip install -r requirements-poetry.txt
          poetry install --sync
          poetry run poe linters
          poetry run poe test
          poetry build
